version: "3.3"
services:
  app:
    image: golang:1.11
    volumes:
      - .:/go/src/whisper
    working_dir: /go/src/whisper
    command: >
      bash -c "go get -u github.com/golang/dep/cmd/dep
      && dep ensure -v && go build -v && ./whisper"
    container_name: whisper
    networks:
      - whisper
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    container_name: whisper_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: whisper
      MYSQL_USER: whisperAdmin
      MYSQL_PASSWORD: whisperAdmin123456
    networks:
      - whisper
    ports:
      - 3306:3306
networks:
  whisper:
    ipam:
      config:
        - subnet: 172.29.0.0/16
volumes:
  db_data:




