version: "3"
services:
  app:
    image: whisper:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: whisper
    networks:
      whisper:
        ipv4_address: 172.29.1.2
    ports:
      - "8086:8086"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    container_name: whisper_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: whisper
      MYSQL_USER: whisperAdmin
      MYSQL_PASSWORD: whisperAdmin123456
    networks:
      whisper:
        ipv4_address: 172.29.1.1
    ports:
      - 3306:3306
networks:
  whisper:
    ipam:
      config:
        - subnet: 172.29.0.0/16
volumes:
  db_data:




